DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS AGENT;

CREATE TABLE AGENT
(
	AGENTID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	FIRSTNAME VARCHAR(50) NOT NULL, 
	LASTNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL
);

INSERT INTO AGENT (USERNAME,FIRSTNAME,LASTNAME,PASSWORD) VALUES ('-','N/A','','111');
INSERT INTO AGENT (USERNAME,FIRSTNAME,LASTNAME,PASSWORD) VALUES ('novak','Novak','Djokovic','222');
INSERT INTO AGENT (USERNAME,FIRSTNAME,LASTNAME,PASSWORD) VALUES ('jeff','Jeff','Alexander','333');
INSERT INTO AGENT (USERNAME,FIRSTNAME,LASTNAME,PASSWORD) VALUES ('marie','Mariana','Johnson','444');

CREATE TABLE CUSTOMER
(
	EMAIL VARCHAR(50) PRIMARY KEY,
	FIRSTNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL
);

INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('bobsmith11@gmail.com','Bob','Smith');
INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('abrown87@outlook.com','Anthony','Brown');
INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('ruby.m5@gmail.com','Ruby','Miller');
INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('woodp88@yahoo.com','Peter','Wood');
INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('m.clark12@gmail.com','Mia','Clark');
INSERT INTO CUSTOMER (EMAIL,FIRSTNAME,LASTNAME) VALUES ('jamie_ol@gmail.com','Jamie','Oliver');

CREATE TABLE BOOKING 
(
	BOOKING_NO SERIAL PRIMARY KEY,
	CUSTOMER VARCHAR(50) NOT NULL REFERENCES CUSTOMER,
	PERFORMANCE VARCHAR(100) NOT NULL,
	PERFORMANCE_DATE DATE NOT NULL,
	BOOKED_BY INTEGER NOT NULL REFERENCES AGENT,
	INSTRUCTION VARCHAR(200)
);

INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('bobsmith11@gmail.com','The Lion King','05/06/2021',2,'I''d like to book 3 additional seats');
INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('abrown87@outlook.com','Romeo & Juliet','11/07/2021',4,'Please cancel 1 seat from my booking');
INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('ruby.m5@gmail.com','Death of a Salesman','27/06/2021',2,'I want to add meals to my booking');
INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('woodp88@yahoo.com','The Lion King','05/06/2021',3,'Can you please waitlist 4 seats?');
INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('m.clark12@gmail.com','Disney''s Frozen','18/07/2021',2,'Please upgrade my seats to Box Seats');
INSERT INTO BOOKING (CUSTOMER,PERFORMANCE,PERFORMANCE_DATE,BOOKED_BY,INSTRUCTION) values ('jamie_ol@gmail.com','Julius Caesar','07/08/2021',1,'');

COMMIT;

CREATE OR REPLACE FUNCTION get_customer_email(required_email VARCHAR(100))
  RETURNS VARCHAR(100) AS $$
  DECLARE
  email VARCHAR(100);
BEGIN
  SELECT CUSTOMER.email INTO email FROM CUSTOMER WHERE required_email = CUSTOMER.email LIMIT 1;
  IF email is NULL THEN RAISE EXCEPTION 'customer does not exist';
  END IF;
  return email;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_agent_id(required_username VARCHAR(100))
  RETURNS INTEGER AS $$
  DECLARE
  id INTEGER;
BEGIN
  SELECT agentid INTO id FROM AGENT WHERE required_username = username LIMIT 1;
  IF id is NULL THEN RAISE EXCEPTION 'Agent does not exist';
  END IF;
  return id;
END;
$$ LANGUAGE plpgsql;
